// <auto-generated />
using BakeryApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakeryApp.Infrastructure.Migrations
{
    [DbContext(typeof(BakeryDbContext))]
    partial class BakeryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.BakeryOfficeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BakeryOffices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "742 Evergreen Terrace",
                            MaxCapacity = 150,
                            Name = "Main Office"
                        },
                        new
                        {
                            Id = 2,
                            Address = "P. Sherman, 42 Wallaby, Sydney",
                            MaxCapacity = 100,
                            Name = "Second Office"
                        });
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.BreadEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PreparationId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.HasIndex("PreparationId");

                    b.ToTable("Breads");

                    b.HasData(
                        new
                        {
                            Name = "Baguette",
                            PreparationId = 1,
                            Price = 2.0
                        },
                        new
                        {
                            Name = "White Bread",
                            PreparationId = 2,
                            Price = 2.5
                        },
                        new
                        {
                            Name = "Milk Bread",
                            PreparationId = 3,
                            Price = 1.5
                        },
                        new
                        {
                            Name = "Hamburguer Bun",
                            PreparationId = 6,
                            Price = 1.0
                        });
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.IngredientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreparationEntityId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreparationEntityId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.OrderDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BreadId")
                        .HasColumnType("int");

                    b.Property<string>("BreadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OrderListEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreadName");

                    b.HasIndex("OrderListEntityId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.OrderListEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BakeryOfficeEntityId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BakeryOfficeEntityId");

                    b.ToTable("OrderLists");
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.PreparationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CookingTemp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CookingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FermentTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Preparations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTemp = "270°C",
                            CookingTime = "15 minutes",
                            FermentTime = "1 day",
                            RestingTime = "0.5 hours"
                        },
                        new
                        {
                            Id = 2,
                            CookingTemp = "180°C",
                            CookingTime = "30 minutes",
                            FermentTime = "4 hours",
                            RestingTime = "1 hour"
                        },
                        new
                        {
                            Id = 3,
                            CookingTemp = "180°C",
                            CookingTime = "15 minutes",
                            FermentTime = "4 hours",
                            RestingTime = "10 minutes"
                        },
                        new
                        {
                            Id = 6,
                            CookingTemp = "180°C",
                            CookingTime = "15 minutes",
                            FermentTime = "4 hours",
                            RestingTime = "0.5 hour"
                        });
                });

            modelBuilder.Entity("BakeryOfficeBread", b =>
                {
                    b.Property<int>("BakeryOfficesId")
                        .HasColumnType("int");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BakeryOfficesId", "MenuName");

                    b.HasIndex("MenuName");

                    b.ToTable("BakeryOfficeBread");

                    b.HasData(
                        new
                        {
                            BakeryOfficesId = 1,
                            MenuName = "Baguette"
                        },
                        new
                        {
                            BakeryOfficesId = 1,
                            MenuName = "White Bread"
                        },
                        new
                        {
                            BakeryOfficesId = 1,
                            MenuName = "Milk Bread"
                        },
                        new
                        {
                            BakeryOfficesId = 2,
                            MenuName = "Baguette"
                        },
                        new
                        {
                            BakeryOfficesId = 2,
                            MenuName = "White Bread"
                        },
                        new
                        {
                            BakeryOfficesId = 2,
                            MenuName = "Hamburguer Bun"
                        });
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.BreadEntity", b =>
                {
                    b.HasOne("BakeryApp.Infrastructure.Persistence.Entities.PreparationEntity", "Preparation")
                        .WithMany()
                        .HasForeignKey("PreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preparation");
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.IngredientEntity", b =>
                {
                    b.HasOne("BakeryApp.Infrastructure.Persistence.Entities.PreparationEntity", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("PreparationEntityId");
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.OrderDetailEntity", b =>
                {
                    b.HasOne("BakeryApp.Infrastructure.Persistence.Entities.BreadEntity", "Bread")
                        .WithMany()
                        .HasForeignKey("BreadName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Infrastructure.Persistence.Entities.OrderListEntity", null)
                        .WithMany("Orders")
                        .HasForeignKey("OrderListEntityId");

                    b.Navigation("Bread");
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.OrderListEntity", b =>
                {
                    b.HasOne("BakeryApp.Infrastructure.Persistence.Entities.BakeryOfficeEntity", null)
                        .WithMany("Orders")
                        .HasForeignKey("BakeryOfficeEntityId");
                });

            modelBuilder.Entity("BakeryOfficeBread", b =>
                {
                    b.HasOne("BakeryApp.Infrastructure.Persistence.Entities.BakeryOfficeEntity", null)
                        .WithMany()
                        .HasForeignKey("BakeryOfficesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryApp.Infrastructure.Persistence.Entities.BreadEntity", null)
                        .WithMany()
                        .HasForeignKey("MenuName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.BakeryOfficeEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.OrderListEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BakeryApp.Infrastructure.Persistence.Entities.PreparationEntity", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
